version: 5.1.0
variant: default
logo: /img/logo.jpg
head:
  favicon: /img/logo.jpg
  manifest:
    name: Jason Dong
    short_name: Jason
    start_url: /archives
    theme_color: "#3273dc"
    background_color:
    display: standalone
    icons:
      - src: /img/logo.jpg
        sizes: 144x144
        type: image/jpg
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
navbar:
  menu:
    首页: /
    文章: /archives
    分类: /categories
    标签: /tags
  links:
    GitHub:
      icon: fab fa-github
      url: https://github.com/JasonDong97
article:
  toc: true
  highlight:
    enable: true
    theme: atom-one-dark
    clipboard: true
    fold: unfolded
  readtime: true
  readmore: true
  update_time: true
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
sidebar:
  left:
    sticky: true
  right:
    sticky: true
footer:
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Download on GitHub:
      icon: fab fa-github
      url: https://github.com/JasonDong97
search:
  type: insight
comment:
  type: changyan
  app_id: cywEhcB4R
  conf: prod_ca49fe0fb8dfbaf8406465c598ed933d
widgets:
  - position: left
    type: profile
    author: Jason Dong
    author_title: 静心净心 戒骄戒躁
    location: 中国·安徽·合肥
    avatar: /img/head.jpg
    avatar_rounded: true
    gravatar:
    follow_link: https://github.com/JasonDong97
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/JasonDong97
      CSDN: https://blog.csdn.net/djx5344
  - position: left
    type: toc
    index: true
    collapsed: true
    depth: 5
  - position: right
    type: recent_posts
  - position: right
    type: links
    links:
      Github: https://github.com
      Hexo: https://hexo.io
      icarus: https://ppoffice.github.io/hexo-theme-icarus/
      icarus主题配置: https://ppoffice.github.io/hexo-theme-icarus/Configuration/icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97-%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/
      畅言云评: https://changyan.kuaizhan.com/
  - position: left
    type: categories
  - position: right
    type: archives
  - position: left
    type: tags
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
    tracking_id:
  busuanzi: false
  gallery: true
  katex: true
  mathjax: true
  outdated_browser: false
  progressbar: false
